name: learn-github-actions-demo
on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '35 11 23 1 *'
  workflow_dispatch:
env:
  SMTP_SERVER: ${{secrets.SMTP_SERVER}}
  SMTP_PORT: ${{secrets.SMTP_PORT}}
  SMTP_LOGIN: ${{secrets.SMTP_LOGIN}}
  SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}

jobs:
  send-email:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run send_inspiration ngoakor12@gmail.com
